version: '3.7'

services:
  app:
    build: 
      context: .
    volumes:
      - ./Marketplace:/Marketplace
    environment:
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=*

  proxy:
    build: 
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app
volumes:
  static_data:
    